# Generated by Django 3.1.2 on 2020-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_auto_20201223_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
