# Generated by Django 3.1.2 on 2020-12-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_auto_20201223_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
