# Generated by Django 3.1.2 on 2020-12-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0009_auto_20201223_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='upload/student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='upload/user'),
        ),
    ]
