# Generated by Django 3.1.2 on 2020-12-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_auto_20201224_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
